### ISSUE TITLE
Status issue in membership product

### ISSUE THREAD

**Issue by mnakalay** [VividWeb/vivid_store#164]
I haven't tested this, just looked throught he code and it seemed weird.

If I am using an external payment processor, the order is marked with a status of "incomplete" but, in the case of membership anyway, the buyer is still registered and added to the groups that give access to the protected content.

Shouldn't they be kept out of the group until the order is marked as complete?

**Comment by brucewyne** [comment]
Potentially. Or go to processing. I think paypal should go to that status rather than complete. That said, maybe an event needs to be fired once the third party verifies the completion of payment. User group assignment, access all gets done after the event.

Thoughts?

**Comment by mnakalay** [comment]
I think you might want to give a choice there. I worked on a client's project where, in case of payment problem or anything like that, she still wanted the buyer to get registered but not put in the proper group. She wanted to make sure she still had access to them even if the payment failed.

So dealing with user groups after the "complete" event sounds like a better idea but maybe the creation of the account could be done before or after depending on a setting?

**Comment by Mesuva** [comment]
What I'd coded up for the memberships was really just a rough version, it was mostly a cut and paste from my Snipcart Memberships add-on, so my plan was always to go back and finish things up. 

With ecommerce where I've needed to add users to groups on some sort of purchase I've done this on the order status change event. That gets fired when a transaction gets put through, or it gets marked manually as paid. That might be how this needs to work.

Is the issue here that to handle Paypal an order needs to be created before the payment has actually been cleared?

**Comment by brucewyne** [comment]
It's not specific to paypal. Technically an invoice would have this issue too.

**Comment by Mesuva** [comment]
Oh yeah, I was assuming it would be for an invoice as well, but that's perhaps a case where you wouldn't enable an invoice for this kind of shop setup I thought.

**Comment by brucewyne** [comment]
There's really a LOT that happens when an order is submitted that needs to be broken out into another method e.g. completeOrder().
- Generate User login
- Clear Shopping cart
- E-mail alerts

These things happen if someone goes through checkout, but backs out of paypal. So we need to add as much of the order details as possible, without doing the following things above. If the payment method used is external, we'll just call the completeOrder() method. Otherwise, the payment method can call it.
