### ISSUE TITLE
Selected Product groups not listed in select box 'In product groups' 

### ISSUE THREAD

**Issue by difi68** [VividWeb/vivid_store#289]
Flow of action:
- selecting some product groups for a product
- save product
  -> groups are visible in products overview
- enter product details 
- choose categories
  -> no selected categorie appears in the select box

**Comment by difi68** [comment]
Possible solution : 
Change line in _/packages/vivid_store/single_pages/dashboard/store/products.php_ 

`<option value="<?php  echo $pgkey;?>" <?php  echo (in_array($pgkey, $pgroups) ? 'selected="selected"' : ''); ?>>  <?php  echo $pglabel; ?></option>`

**Comment by Mesuva** [comment]
I'm not able to replicate this. I can add product groups (and categories), save them, return to the product and see the ones that were originally selected.

Looking at the code, I think that line is already as per your suggestion:
https://github.com/VividWeb/vivid_store/blob/development/single_pages/dashboard/store/products.php#L220

Are you using a version from github, or the marketplace version?

**Comment by difi68** [comment]
Hi, i'm using the marketplace version 3.0.1. So can you tell me, which version should use ? The one directly out of github repo or will there be a new official version nearby ?
Thx.

**Comment by tom-rice** [comment]
The marketplace version has this line in single_pages/dashboard/store/products.php:

`<option value="<?php  echo $pgkey;?>" <?php  echo (in_array($pgkey, $productgroups) ? 'selected="selected"' : ''); ?>>  <?php  echo $pglabel; ?></option>`

But github has this:

`<option value="<?php  echo $pgkey;?>" <?php  echo (in_array($pgkey, $pgroups) ? 'selected="selected"' : ''); ?>>  <?php  echo $pglabel; ?></option>`

So if downloaded from Github development it works correctly, because $productgroups should be $pgroups.

It was originally fixed on September 17th but did not seem to make it into the 3.0.1 release on Sep 21st?

**Comment by brucewyne** [comment]
Makes sense. That said, we're about to release 3.1 into the marketplace which has a lot of goodies/fixes. Should stabilize the release a bit.

**Comment by tom-rice** [comment]
Awesome to hear looking forward to it :)
