### ISSUE TITLE
Tax option need a label/name

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#33]
Really just another config field that can be referred to for invoices, etc.

(also, do we need to be able to configure multiple taxes?)

**Comment by brucewyne** [comment]
I've often wondered that. Why would you need multiple taxes, and if you don't have multiple taxes, then why do you need a name.

The obvious answer is multiple store locations. If a store has a location in New York and California, then they need to charge a certain, and different, rate if the shipping address matches either of those.

This honestly makes me wonder: 1. This is likely low on our priority poll (not that it isn't a need). 2. Is this a good opportunity for someone such as yourself to create a premium add-on? Especially since this isn't a likely every-day need. Or do you think this is something that should be baked in?

**Comment by Mesuva** [comment]
I've never used multiple taxes, but that could be because in Aus we really only have the one tax we'd need to consider and the shops I've built for overseas haven't handled taxes pretty easily.

My understanding of multiple taxes is for some places in the world where two separate taxes might apply:
- State tax 5.5%
- Fancy tax 3.2%

**Comment by brucewyne** [comment]
I think where this is going to get used most is big stores with multiple locations. Because of, not the small percentage of stores that need it, but the small percentage of stores that need it and would use this product as opposed to a full blown ecom solution like magento, I feel like this is a feature best shelved for someone to make as an add-on.

I'm open to being corrected and shown where a lot of people would need this.

If you start considering this on the grounds of multiple stores in different states/countries with different tax codes (what I think 90% of the need for this would be), then it starts more conversations about inventory location, shipping method origin locations....

I don't know.
