### ISSUE TITLE
List of products in checkout?

### ISSUE THREAD

**Issue by Mesuva** [VividWeb/vivid_store#71]
On the checkout screen the cart totals are displayed, but I think it would make sense to also list the breakdown of the products and quantities in the cart above the totals.

**Comment by brucewyne** [comment]
Yes! If you noticed, the div for that right column is aptly named "checkout-cart-view" because I initially wanted the cart there as well.

Along this thinking, the real ideal is also making a Cart List Block that you could add anywhere and sticking that block in an area on that page. Having it as a block would allow devs to place the cart constantly in view on the right sidebar or something.

**Comment by brucewyne** [comment]
Bitchin'
