### ISSUE TITLE
multiple tax keys

### ISSUE THREAD

**Issue by Remo** [VividWeb/vivid_store#75]
Quite a few online shops I've built had two or more tax keys and not just one which is either used or not.

**Comment by brucewyne** [comment]
This was discussed before, and we changed a few things to start making that a little easier to do. It just hasn't been done yet. I'm open to it. I first thought that it would be used in a business that had multiple store locations with different tax codes, but realized I was wrong about that. 

So that said, it may be long down the list of our immediate priorities. I'm marking it as Help Wanted in case anyone wants to contribute that. I could also see someone making a premium add-on for it. I wouldn't be mad at either. If it goes unaddressed for long enough and there's some demand for it, maybe we can circle back to it.

**Comment by Remo** [comment]
It's good to know you're open to it. Knowthing that makes this package a bit more useable for us! If we need it, we could contribute some code, not as an add-on but rather a pull request.

**Comment by brucewyne** [comment]
Of course I'm open to it :) I'm pretty much open to anything that benefits the store.
